#!/bin/sh
# Copyright (C) 2009, 2010 Robert Lehmann

cat README.rst - <<EOF

Reference
---------

EOF

python <<EOF
from textwrap import dedent
from libleipzig import services

TEMPLATE = """
%(label)s
%(underline)s

:Returns: %(returns)s

%(doc)s
"""

for name, service in services.iteritems():
    label = service._label
    print TEMPLATE % dict(label=label,
                          underline="^" * len(label),
                          name=name,
                          returns=func._retlabel,
                          doc=dedent(service._doc))
EOF
